name: flutter_setup
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  intl: ^0.20.1
  go_router: ^14.6.2
  get: ^4.6.6
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/open-book.png"
  min_sdk_android: 23


flutter:

  uses-material-design: true

  assets:
    - assets/images/
